### ISSUE TITLE
Alpert correlaton opens with pre-populated data

### ISSUE THREAD

**Issue by simonsantama** [fire-library/openfire#15]
Currently, the Alpert correlation is opening up with pre-populated data when first used. It should open with all values in "0".

**Comment by JamieMaclean** [comment]
Addressed in 89189097a3ba8508a22803ad6ccd3e944dc43288

**Comment by simonsantama** [comment]
I am still seeing this occur (pulled from git at 17:00 today)
